### ISSUE TITLE
`java.lang.Exception: does not exist` when preparing candidate block after node restart.

### ISSUE THREAD

**Issue by oskin1** [oskin1/EncryCore#4]

**Comment by oskin1** [comment]
[scorex-akka.actor.default-dispatcher-2] >> [WARN ] encry.local.mining.EncryMiner >> 15:28:09.755 Error when trying to generate candidate: 
java.lang.Exception: does not exist
	at scorex.crypto.authds.avltree.batch.Remove.$anonfun$updateFn$5(Operation.scala:61)
	at scorex.crypto.authds.avltree.batch.AuthenticatedTreeOps.modifyHelper$1(AuthenticatedTreeOps.scala:162)
	at scorex.crypto.authds.avltree.batch.AuthenticatedTreeOps.modifyHelper$1(AuthenticatedTreeOps.scala:183)
	at scorex.crypto.authds.avltree.batch.AuthenticatedTreeOps.modifyHelper$1(AuthenticatedTreeOps.scala:183)
	at scorex.crypto.authds.avltree.batch.AuthenticatedTreeOps.modifyHelper$1(AuthenticatedTreeOps.scala:183)
	at scorex.crypto.authds.avltree.batch.AuthenticatedTreeOps.modifyHelper$1(AuthenticatedTreeOps.scala:183)
	at scorex.crypto.authds.avltree.batch.AuthenticatedTreeOps.modifyHelper$1(AuthenticatedTreeOps.scala:183)
	at scorex.crypto.authds.avltree.batch.AuthenticatedTreeOps.modifyHelper$1(AuthenticatedTreeOps.scala:183)
	at scorex.crypto.authds.avltree.batch.AuthenticatedTreeOps.modifyHelper$1(AuthenticatedTreeOps.scala:183)
	at scorex.crypto.authds.avltree.batch.AuthenticatedTreeOps.modifyHelper$1(AuthenticatedTreeOps.scala:183)
	at scorex.crypto.authds.avltree.batch.AuthenticatedTreeOps.$anonfun$returnResultOfOneOperation$1(AuthenticatedTreeOps.scala:400)
	at scala.util.Try$.apply(Try.scala:209)
	at scorex.crypto.authds.avltree.batch.AuthenticatedTreeOps.returnResultOfOneOperation(AuthenticatedTreeOps.scala:111)
	at scorex.crypto.authds.avltree.batch.AuthenticatedTreeOps.returnResultOfOneOperation$(AuthenticatedTreeOps.scala:111)
	at scorex.crypto.authds.avltree.batch.BatchAVLProver.returnResultOfOneOperation(BatchAVLProver.scala:21)
	at scorex.crypto.authds.avltree.batch.BatchAVLProver.$anonfun$performOneOperation$1(BatchAVLProver.scala:164)
	at scala.util.Try$.apply(Try.scala:209)
	at scorex.crypto.authds.avltree.batch.BatchAVLProver.performOneOperation(BatchAVLProver.scala:162)
	at scorex.crypto.authds.avltree.batch.PersistentBatchAVLProver.performOneOperation(PersistentBatchAVLProver.scala:21)
	at encry.view.state.UtxoState.$anonfun$proofsForTransactions$7(UtxoState.scala:128)
	at scala.util.Success.flatMap(Try.scala:247)
	at encry.view.state.UtxoState.$anonfun$proofsForTransactions$6(UtxoState.scala:127)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
	at scala.collection.immutable.List.foldLeft(List.scala:86)
	at encry.view.state.UtxoState.$anonfun$proofsForTransactions$3(UtxoState.scala:126)
	at scala.util.Try$.apply(Try.scala:209)
	at encry.view.state.UtxoState.proofsForTransactions(UtxoState.scala:116)
	at encry.local.mining.EncryMiner.$anonfun$prepareCandidate$3(EncryMiner.scala:142)
	at scala.util.Try$.apply(Try.scala:209)
	at encry.local.mining.EncryMiner.$anonfun$prepareCandidate$1(EncryMiner.scala:101)
	at scorex.core.NodeViewHolder$$anonfun$getCurrentInfo$1.applyOrElse(NodeViewHolder.scala:378)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at encry.view.EncryNodeViewHolder.aroundReceive(EncryNodeViewHolder.scala:24)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
	at akka.actor.ActorCell.invoke(ActorCell.scala:496)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
